### ISSUE TITLE
node-gyp fails for grunt-inspector

### ISSUE THREAD

**Issue by derMani** [sincraianul/generator-angular-material-fullstack#3]
npm install fails with node > 4.2 and npm 3.4.1 

```
ake: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/user/workspace/git/app/node_modules/v8-debug/build/debug/v0.4.6/node-v47-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/user/workspace/git/app/node_modules/v8-debug/build/debug/v0.4.6/node-v47-darwin-x64"
gyp ERR! cwd /Users/user/workspace/git/app/node_modules/v8-debug
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/user/workspace/git/app/node_modules/v8-debug/build/debug/v0.4.6/node-v47-darwin-x64/debug.node --module_name=debug --module_path=/Users/user/workspace/git/app/node_modules/v8-debug/build/debug/v0.4.6/node-v47-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/user/workspace/git/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/Users/user/workspace/git/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/user/workspace/git/app/node_modules/v8-debug
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.15
node-pre-gyp ERR! not ok 
```

I've seen this problem also for the "generator-angular-fullstack" generator and it is related to the grunt-inspector.

Grunt-inspector must be updated in the "package.json" 

from 

```
"grunt-node-inspector": "~0.1.5"
```

to 

```
"grunt-node-inspector": "^0.4.1"
```

Then npm install won't fail.

Best regards

derMani

**Comment by jkieley** [comment]
+1 (Great solution)

**Comment by Richardssen** [comment]
Thanks so much

**Comment by oliverkierepka** [comment]
thanks that worked for me to... can you please commit the change in the yo config and package.json? thanks
